pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    // environment{
    //     DEBUG = 'true'
    // }
    parameters {
        choice(name: 'ACTION', choices: ['apply','destroy'], description: 'select Action')
    }
    stages {
        stage('Init and plan') {
            steps {
                 withAWS(region: 'us-east-1', credentials: 'aws-creds')
                 sh """
                    cd 00-vpc
                    terraform init -reconfigure
                    sh 'terraform paln -out=tfplan'
                 """
            }
        }
        
        
        
        // stage('Docker build') {
        //     steps {
        //         sh """
        //         docker build -t riyacham/backend:${appVersion} .
        //         docker images
        //         """
        //     }
        // }
    
       
        
    }
    post {
        always{
            echo "this section run always"
            deleteDir()
        }
        success{
            echo "this section run when pipeline success"
        }
        failure{
            echo "this section run when pipeline fails"
        }
    }

}